### ISSUE TITLE
Project issues on GitHub

### ISSUE THREAD

**Issue by brodybits** [wollardj/node-simple-plist#21]
Thanks for making the modernized `1.0.0` release. I spotted the following issues with this project on GitHub:
- [x] Travis CI does not seem to be enabled for PRs (did not seem to be run when I raised PR #20)
- [x] Travis CI does not seem to be run on recent commits in <https://github.com/wollardj/node-simple-plist/commits/master>
- [x] The default branch of this project seems to be `develop`, which does not have any commits since 2016.

I would also recommend increasing the version number and adding "-dev" to the end after publishing each release. This way whenever someone raises a PR it would not look like it is a released version.

**Comment by wollardj** [comment]
> - [x] The default branch of this project seems to be develop, which does not have any commits since 2016.

I updated `develop` last night before merging into `master` to cut the release, but I forgot to `push --all`. 😃 

> I would also recommend increasing the version number and adding "-dev" to the end after publishing each release. This way whenever someone raises a PR it would not look like it is a released version.

Not sure what you mean by this. I'm assuming you're referencing a practice you've seen elsewhere, so maybe it would make more sense to me if you could link to an example or some documentation that I can look into.

**Comment by wollardj** [comment]
Also, I've got an open ticket with TravisCI to migrate this project to their newer platform. Open source projects like this one are not given priority migration, but they have offered to let me participate in their beta migration program. As soon as they flip the appropriate bits on my account, I'll migrate the project and make sure GitHub is providing the appropriate insight into builds.

But for now, we wait. ⏲

**Comment by brodybits** [comment]
Thanks for fixing `develop`. Not your fault about the Travis CI, would like to see it tracked though. Link to an example of using "-dev" version is coming next.

**Comment by brodybits** [comment]
An example of using "-dev" is in <https://github.com/apache/cordova-coho/blob/master/docs/storing-repo-versions-design.md#cordova-platform-repositories-1>:

> The version number should correspond closely to the git branch.
> [...]
> The **master** branch should always have a version number ending in "-dev", which indicates the version currently being developed.

and then:

> A fresh release branch should change the version to an "-rc1" version, and then change to the unqualified version number when it is released.

There seems to be some controversy around this idea. There is an interesting discussion in <https://gist.github.com/nzakas/7633640>, with most people against this idea. But I find an excellent argument for this idea in (<https://gist.github.com/nzakas/7633640#gistcomment-957567>):

> In my experience, people blindly install from GitHub and when I ask them what version they're using, they say, "the latest." I usually have to dig in to figure out if they installed from npm or from GitHub. :(

**Comment by wollardj** [comment]
Looks like the Travis-CI migration resolved the issues. If you checkout #22 you can see the ci build statuses that took place.

**Comment by brodybits** [comment]
CI build is now green on both PR #22 and default `develop` branch, thanks again for your efforts!
